import "./bootstrap";
import "../assets/js/vendor/modernizr.min.js";
import "../assets/js/vendor/jquery.js";
import "../assets/js/vendor/bootstrap.min.js";
import "../assets/js/vendor/sal.js";
import "../assets/js/vendor/js.cookie.js";
import "../assets/js/vendor/jquery.style.switcher.js";
import "../assets/js/vendor/swiper.js";
import "../assets/js/vendor/jquery-appear.js";
import "../assets/js/vendor/odometer.js";
import "../assets/js/vendor/backtotop.js";
import "../assets/js/vendor/text-type.js";
import "../assets/js/vendor/jquery-one-page-nav.js";
import "../assets/js/vendor/bootstrap-select.min.js";
import "../assets/js/vendor/jquery-ui.js";
import "../assets/js/vendor/magnify-popup.min.js";
import "../assets/js/vendor/paralax-scroll.js";
import "../assets/js/vendor/paralax.min.js";
import "../assets/js/vendor/countdown.js";
import "../assets/js/vendor/plyr.js";
import "../assets/js/vendor/jodit.min.js";
import "../assets/js/vendor/Sortable.min.js";
import "../assets/js/vendor/livewire-event-handler.js";
import {createCodeEditor} from "../assets/js/vendor/code-editor.js";

window.createCodeEditor = createCodeEditor;

import Plyr from "plyr";
window.Plyr = Plyr;
import "../assets/js/main.js";
